/** Curated liquid ETFs and widely held stocks for quick selection. */
export const POPULAR_TICKERS: { symbol: string; name: string }[] = [
  { symbol: "VOO", name: "Vanguard S&P 500 ETF" },
  { symbol: "SPY", name: "SPDR S&P 500 ETF" },
  { symbol: "QQQ", name: "Invesco Nasdaq-100 ETF" },
  { symbol: "IWM", name: "iShares Russell 2000 ETF" },
  { symbol: "DIA", name: "SPDR Dow Jones ETF" },
  { symbol: "VTI", name: "Vanguard Total Stock Market ETF" },
  { symbol: "VXUS", name: "Vanguard Total International Stock ETF" },
  { symbol: "BND", name: "Vanguard Total Bond Market ETF" },
  { symbol: "SCHD", name: "Schwab US Dividend Equity ETF" },
  { symbol: "VUG", name: "Vanguard Growth ETF" },
  { symbol: "VTV", name: "Vanguard Value ETF" },
  { symbol: "XLK", name: "Technology Select Sector SPDR" },
  { symbol: "XLE", name: "Energy Select Sector SPDR" },
  { symbol: "XLF", name: "Financial Select Sector SPDR" },
  { symbol: "GLD", name: "SPDR Gold Shares" },
  { symbol: "TLT", name: "iShares 20+ Year Treasury Bond ETF" },
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft Corp." },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)" },
  { symbol: "AMZN", name: "Amazon.com Inc." },
  { symbol: "META", name: "Meta Platforms Inc." },
  { symbol: "NVDA", name: "NVIDIA Corp." },
  { symbol: "BRK.B", name: "Berkshire Hathaway (Class B)" },
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "MA", name: "Mastercard Inc." },
  { symbol: "UNH", name: "UnitedHealth Group Inc." },
];
